server:
    port: 8081
    servlet:
        context-path: /resource-server

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://192.168.2.13:10080/auth/realms/spring
                    jwk-set-uri: http://192.168.2.13:10080/auth/realms/spring/protocol/openid-connect/certs
        user:
            name: bernd
            password: 4711

logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure:
                        security: INFO